// <auto-generated />
using Code_First_Make_2_Tables.Dal;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Code_First_2_Table_WEB.Migrations
{
    [DbContext(typeof(schoolDBContext))]
    [Migration("20260628123825_1")]
    partial class _1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Code_First_Make_2_Tables.Model.School", b =>
                {
                    b.Property<int>("schoolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("city")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("schoolName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("schoolId");

                    b.ToTable("schools");
                });

            modelBuilder.Entity("Code_First_Make_2_Tables.Model.Teacher", b =>
                {
                    b.Property<int>("teacherId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("schoolId")
                        .HasColumnType("int");

                    b.Property<string>("subject")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("tName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("teacherId");

                    b.HasIndex("schoolId");

                    b.ToTable("teachers");
                });

            modelBuilder.Entity("Code_First_Make_2_Tables.Model.Teacher", b =>
                {
                    b.HasOne("Code_First_Make_2_Tables.Model.School", "school")
                        .WithMany()
                        .HasForeignKey("schoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("school");
                });
#pragma warning restore 612, 618
        }
    }
}
