DELIMITER //

CREATE trigger AFTER_TRANSACTIION_INSERT
AFTER insert ON TRANSACTIONHISTORY
FOR each row
BEGIN
	IF NEW.TRANSACTION_TYPE = 'DEPOSIT' THEN
    UPDATE ACCOUNTS SET BALANCE = BALANCE + NEW.ACCOUNT WHERE ACCOUNT_ID = NEW.ACCOUNT_ID;
    elseif NEW.TRANSACTION_TYPE = 'WITHDRAW' THEN
    UPDATE ACCOUNTS SET BALANCE = BALANCE = BALANCE - NEW.ACCOUNT_ID = NEW.ACCOUNT_ID;
	end if;
END
DELIMITER ;
    