package com.app.config;

import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.security.config.Customizer;
import org.springframework.security.config.annotation.web.builders.HttpSecurity;
import org.springframework.security.config.annotation.web.configuration.EnableWebSecurity;
import org.springframework.security.config.http.SessionCreationPolicy;
import org.springframework.security.web.SecurityFilterChain;

/**
 * Configuration class for application security settings.
 */
@Configuration // Marks this class as a source of bean definitions for the Spring context.
@EnableWebSecurity // Enables Spring Security's web security support and integrates it with Spring MVC.
public class SecurityConfig {

	/**
	 * Configures the security filter chain that handles HTTP requests.
	 * * @param http the HttpSecurity object to configure
	 * @return the built SecurityFilterChain
	 * @throws Exception if an error occurs during configuration
	 */
	@Bean
	SecurityFilterChain securityFilterChain(HttpSecurity http) throws Exception {
		
		// 1. Disable CSRF (Cross-Site Request Forgery) protection.
		// Commonly done for stateless REST APIs where JWTs or basic auth are used instead of cookies.
		http.csrf(customizer -> customizer.disable());
		
		// 2. Protect all incoming HTTP requests.
		// This ruleset ensures that ANY request made to the application must be authenticated.
		http.authorizeHttpRequests(request -> request.anyRequest().authenticated());
		
		// 3. Enable Form-Based Login authentication with default configurations.
		// Provides a default login page generated by Spring Security for browser-based users.
		http.formLogin(Customizer.withDefaults());
		
		// 4. Enable HTTP Basic authentication with default configurations.
		// Allows clients to pass credentials (username/password) via the 'Authorization' header.
		http.httpBasic(Customizer.withDefaults());
		
		// 5. Configure session management to be stateless.
		// Spring Security will never create an HttpSession and will never use it to obtain the SecurityContext.
		// Ideal for REST APIs, though note that formLogin (above) typically relies on standard sessions to function properly.
		http.sessionManagement(session -> session.sessionCreationPolicy(SessionCreationPolicy.STATELESS));
		
		// Build and return the configured SecurityFilterChain instance.
		return http.build();
	}
}